import { amenity, defineField } from '../defineField.js';

/**
 * Property fields (Part III §4).
 *
 * Amenities and utilities are structured selections, never description-only
 * text -- that is an explicit completion criterion, and it is what makes them
 * filterable.
 *
 * `bedrooms`, `bathrooms` and `size_sqm` stay in the existing
 * `property_details` columns so current listings, cards and filters keep
 * working unchanged. Everything else is an attribute.
 */

export const PROPERTY_SUBTYPES = Object.freeze([
  { value: 'residential', label: 'Residential' },
  { value: 'commercial', label: 'Commercial' },
  { value: 'industrial', label: 'Industrial' },
  { value: 'agricultural', label: 'Agricultural' },
  { value: 'land', label: 'Land' },
]);

const BUILT = ['residential', 'commercial', 'industrial'];
const HABITABLE = ['residential'];

export const PROPERTY_FIELDS = Object.freeze([
  // --- Overview -----------------------------------------------------------
  defineField({
    id: 'listing_type',
    label: 'Offer type',
    input: 'select',
    section: 'overview',
    order: 10,
    requirement: 'required',
    options: [
      { value: 'sale', label: 'For sale' },
      { value: 'rent', label: 'To rent' },
      { value: 'lease', label: 'To lease' },
      { value: 'short_stay', label: 'Short stay' },
    ],
    filterable: true,
    searchable: true,
    onCard: true,
    storage: 'column',
    column: 'listing_type',
  }),
  defineField({
    id: 'property_type',
    label: 'Property type',
    input: 'select',
    section: 'overview',
    order: 20,
    requirement: 'required',
    options: [
      { value: 'house', label: 'House' },
      { value: 'apartment', label: 'Apartment' },
      { value: 'townhouse', label: 'Townhouse' },
      { value: 'cottage', label: 'Cottage' },
      { value: 'office', label: 'Office' },
      { value: 'retail', label: 'Retail space' },
      { value: 'warehouse', label: 'Warehouse' },
      { value: 'factory', label: 'Factory' },
      { value: 'farm', label: 'Farm' },
      { value: 'stand', label: 'Stand / plot' },
    ],
    filterable: true,
    onCard: true,
    storage: 'column',
    column: 'property_type',
  }),

  // --- Specifications -----------------------------------------------------
  defineField({
    id: 'bedrooms',
    label: 'Bedrooms',
    input: 'number',
    section: 'specifications',
    order: 10,
    requirement: 'required',
    showWhen: { field: 'subtype', in: HABITABLE },
    validation: { min: 0, max: 50, step: 1 },
    filterable: true,
    onCard: true,
    storage: 'column',
    column: 'bedrooms',
  }),
  defineField({
    id: 'bathrooms',
    label: 'Bathrooms',
    input: 'number',
    section: 'specifications',
    order: 20,
    requirement: 'required',
    showWhen: { field: 'subtype', in: HABITABLE },
    validation: { min: 0, max: 50, step: 1 },
    filterable: true,
    onCard: true,
    storage: 'column',
    column: 'bathrooms',
  }),
  defineField({
    id: 'size_sqm',
    label: 'Internal area',
    input: 'number',
    section: 'specifications',
    order: 30,
    showWhen: { field: 'subtype', in: BUILT },
    unit: 'sqm',
    validation: { min: 1, max: 1000000 },
    filterable: true,
    onCard: true,
    storage: 'column',
    column: 'size_sqm',
  }),
  defineField({
    id: 'land_size_sqm',
    label: 'Land size',
    input: 'number',
    section: 'specifications',
    order: 40,
    requiredWhen: { field: 'subtype', in: ['land', 'agricultural'] },
    unit: 'sqm',
    validation: { min: 1, max: 100000000 },
    filterable: true,
  }),
  defineField({
    id: 'floor_number',
    label: 'Floor number',
    input: 'number',
    section: 'specifications',
    order: 50,
    showWhen: { field: 'property_type', in: ['apartment', 'office', 'retail'] },
    validation: { min: -5, max: 200, step: 1 },
  }),
  defineField({
    id: 'total_floors',
    label: 'Total floors',
    input: 'number',
    section: 'specifications',
    order: 60,
    showWhen: { field: 'subtype', in: BUILT },
    validation: { min: 1, max: 200, step: 1 },
  }),
  defineField({
    id: 'construction_year',
    label: 'Year built',
    input: 'number',
    section: 'specifications',
    order: 70,
    showWhen: { field: 'subtype', in: BUILT },
    validation: { min: 1800, max: 2100, step: 1 },
    allowUnknown: true,
    filterable: true,
  }),
  defineField({
    id: 'property_condition',
    label: 'Condition',
    input: 'select',
    section: 'specifications',
    order: 80,
    showWhen: { field: 'subtype', in: BUILT },
    options: [
      { value: 'new', label: 'New' },
      { value: 'excellent', label: 'Excellent' },
      { value: 'good', label: 'Good' },
      { value: 'fair', label: 'Fair' },
      { value: 'needs_work', label: 'Needs work' },
    ],
    filterable: true,
  }),
  defineField({
    id: 'tenure',
    label: 'Ownership / tenure',
    input: 'select',
    section: 'specifications',
    order: 90,
    options: [
      { value: 'freehold', label: 'Freehold' },
      { value: 'leasehold', label: 'Leasehold' },
      { value: 'sectional_title', label: 'Sectional title' },
      { value: 'share_block', label: 'Share block' },
      { value: 'communal', label: 'Communal' },
    ],
    allowUnknown: true,
    filterable: true,
  }),
  defineField({
    id: 'furnishing',
    label: 'Furnishing',
    input: 'select',
    section: 'specifications',
    order: 100,
    showWhen: { field: 'subtype', in: HABITABLE },
    options: [
      { value: 'furnished', label: 'Furnished' },
      { value: 'semi_furnished', label: 'Semi-furnished' },
      { value: 'unfurnished', label: 'Unfurnished' },
    ],
    filterable: true,
    onCard: true,
  }),

  // --- Parking ------------------------------------------------------------
  defineField({
    id: 'parking_type',
    label: 'Parking',
    input: 'select',
    section: 'features',
    order: 10,
    options: [
      { value: 'none', label: 'None' },
      { value: 'street', label: 'On street' },
      { value: 'driveway', label: 'Driveway' },
      { value: 'carport', label: 'Carport' },
      { value: 'garage', label: 'Garage' },
      { value: 'secure_bay', label: 'Secure bay' },
    ],
    filterable: true,
  }),
  defineField({
    id: 'parking_spaces',
    label: 'Parking spaces',
    input: 'number',
    section: 'features',
    order: 20,
    showWhen: { field: 'parking_type', not: ['none'] },
    validation: { min: 0, max: 500, step: 1 },
    filterable: true,
  }),

  // --- Utilities: structured, not prose -----------------------------------
  amenity('municipal_water', 'Municipal water', 'features', 30),
  amenity('borehole', 'Borehole', 'features', 40),
  amenity('water_tank', 'Water tank', 'features', 50),
  amenity('grid_electricity', 'Grid electricity', 'features', 60),
  amenity('solar_power', 'Solar power', 'features', 70),
  amenity('generator', 'Generator', 'features', 80),
  amenity('backup_power', 'Other backup power', 'features', 90),
  defineField({
    id: 'internet',
    label: 'Internet',
    input: 'select',
    section: 'features',
    order: 100,
    options: [
      { value: 'fibre', label: 'Fibre' },
      { value: 'wireless', label: 'Wireless' },
      { value: 'adsl', label: 'ADSL' },
      { value: 'none', label: 'None' },
    ],
    allowUnknown: true,
    filterable: true,
  }),

  // --- Amenities ----------------------------------------------------------
  defineField({
    id: 'security_features',
    label: 'Security',
    input: 'multiselect',
    section: 'features',
    order: 110,
    options: [
      { value: 'wall', label: 'Walled' },
      { value: 'electric_fence', label: 'Electric fence' },
      { value: 'gate_motor', label: 'Gate motor' },
      { value: 'alarm', label: 'Alarm' },
      { value: 'guard', label: 'On-site guard' },
      { value: 'cctv', label: 'CCTV' },
      { value: 'estate_security', label: 'Estate security' },
    ],
    filterable: true,
  }),
  amenity('garden', 'Garden', 'features', 120),
  amenity('balcony', 'Balcony', 'features', 130),
  amenity('terrace', 'Terrace', 'features', 140),
  amenity('swimming_pool', 'Swimming pool', 'features', 150, { onCard: true }),
  amenity('gym', 'Gym', 'features', 160),
  amenity('lift', 'Lift', 'features', 170),
  amenity('wheelchair_access', 'Wheelchair access', 'features', 180),
  amenity('staff_quarters', 'Staff quarters', 'features', 190),
  amenity('storage', 'Storage', 'features', 200),
  defineField({
    id: 'pet_policy',
    label: 'Pets',
    input: 'select',
    section: 'features',
    order: 210,
    showWhen: { field: 'listing_type', in: ['rent', 'lease', 'short_stay'] },
    options: [
      { value: 'allowed', label: 'Allowed' },
      { value: 'negotiable', label: 'Negotiable' },
      { value: 'not_allowed', label: 'Not allowed' },
    ],
    filterable: true,
  }),

  // --- Commercial / industrial only ---------------------------------------
  defineField({
    id: 'loading_bays',
    label: 'Loading bays',
    input: 'number',
    section: 'features',
    order: 220,
    showWhen: { field: 'subtype', in: ['commercial', 'industrial'] },
    validation: { min: 0, max: 200, step: 1 },
    filterable: true,
  }),
  amenity('warehouse_facilities', 'Warehouse facilities', 'features', 230, {
    showWhen: { field: 'subtype', in: ['commercial', 'industrial'] },
  }),
  defineField({
    id: 'zoning',
    label: 'Zoning',
    input: 'text',
    section: 'specifications',
    order: 110,
    showWhen: { field: 'subtype', in: ['commercial', 'industrial', 'agricultural', 'land'] },
    validation: { maxLength: 80 },
  }),
  defineField({
    id: 'permitted_use',
    label: 'Permitted use',
    input: 'text',
    section: 'specifications',
    order: 120,
    showWhen: { field: 'subtype', in: ['commercial', 'industrial', 'agricultural', 'land'] },
    validation: { maxLength: 200 },
  }),

  // --- Recurring costs ----------------------------------------------------
  defineField({
    id: 'rates_amount',
    label: 'Council rates',
    input: 'number',
    section: 'pricing',
    order: 10,
    unit: 'per_month',
    validation: { min: 0, max: 10000000 },
  }),
  defineField({
    id: 'levies_amount',
    label: 'Levies',
    input: 'number',
    section: 'pricing',
    order: 20,
    unit: 'per_month',
    validation: { min: 0, max: 10000000 },
  }),
  defineField({
    id: 'deposit_amount',
    label: 'Deposit',
    input: 'number',
    section: 'pricing',
    order: 30,
    showWhen: { field: 'listing_type', in: ['rent', 'lease'] },
    validation: { min: 0, max: 10000000 },
  }),

  // --- Availability -------------------------------------------------------
  defineField({
    id: 'occupancy_status',
    label: 'Occupancy',
    input: 'select',
    section: 'availability',
    order: 10,
    options: [
      { value: 'vacant', label: 'Vacant' },
      { value: 'owner_occupied', label: 'Owner occupied' },
      { value: 'tenanted', label: 'Tenanted' },
    ],
    filterable: true,
  }),
  defineField({
    id: 'available_from',
    label: 'Available from',
    input: 'date',
    section: 'availability',
    order: 20,
    filterable: true,
  }),
]);
