begin;
create extension if not exists pgtap with schema extensions;
select extensions.no_plan();

select extensions.is((select count(*)::bigint from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname='private' and p.proname='record_recommendation_event' and pg_get_function_identity_arguments(p.oid)='p_event_type text, p_listing_id uuid, p_seller_id uuid, p_anonymous_session_id uuid, p_recommendation_request_id uuid, p_recommendation_service text, p_reason_code text, p_context jsonb' and pg_get_function_result(p.oid)='uuid' and l.lanname='plpgsql' and p.prosecdef and p.provolatile='v' and p.pronargdefaults=7 and p.proconfig=array['search_path=""']::text[] and md5(replace(p.prosrc,E'\r\n',E'\n'))='53f09ebe32d390272c80a2c411cb4e70'),1::bigint,'one locked recommendation-event definer lives in private');
select extensions.is((select count(*)::bigint from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname='public' and p.proname='record_recommendation_event' and pg_get_function_identity_arguments(p.oid)='p_event_type text, p_listing_id uuid, p_seller_id uuid, p_anonymous_session_id uuid, p_recommendation_request_id uuid, p_recommendation_service text, p_reason_code text, p_context jsonb' and pg_get_function_result(p.oid)='uuid' and l.lanname='sql' and not p.prosecdef and p.provolatile='v' and p.pronargdefaults=7 and p.proconfig=array['search_path=""']::text[] and position('private.record_recommendation_event(' in p.prosrc)>0),1::bigint,'one public recommendation-event invoker wrapper preserves seven defaults');
select extensions.is((select count(*)::bigint from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) x where n.nspname in ('public','private') and p.proname='record_recommendation_event' and x.grantee=0 and x.privilege_type='EXECUTE'),0::bigint,'no PUBLIC execute grant remains');
select extensions.ok(has_function_privilege('anon','public.record_recommendation_event(text,uuid,uuid,uuid,uuid,text,text,jsonb)','EXECUTE') and has_function_privilege('authenticated','public.record_recommendation_event(text,uuid,uuid,uuid,uuid,text,text,jsonb)','EXECUTE') and has_function_privilege('service_role','public.record_recommendation_event(text,uuid,uuid,uuid,uuid,text,text,jsonb)','EXECUTE'),'public wrapper preserves role grants');
select extensions.ok(has_function_privilege('anon','private.record_recommendation_event(text,uuid,uuid,uuid,uuid,text,text,jsonb)','EXECUTE') and has_function_privilege('authenticated','private.record_recommendation_event(text,uuid,uuid,uuid,uuid,text,text,jsonb)','EXECUTE') and has_function_privilege('service_role','private.record_recommendation_event(text,uuid,uuid,uuid,uuid,text,text,jsonb)','EXECUTE'),'private implementation preserves role grants');
select extensions.is((select count(*)::bigint from pg_proc p join pg_namespace n on n.oid=p.pronamespace where position('record_recommendation_event(' in p.prosrc)>0 and not(n.nspname in('public','private') and p.proname='record_recommendation_event')),0::bigint,'no stored function depends on the public identity');
select extensions.is((select count(*)::bigint from pg_policies where position('record_recommendation_event(' in coalesce(qual,''))>0 or position('record_recommendation_event(' in coalesce(with_check,''))>0),0::bigint,'no RLS policy depends on the public identity');

set local role anon;
select extensions.throws_ok($$select public.record_recommendation_event('unsupported')$$,'22023','unsupported recommendation event type','public wrapper preserves default arguments and event validation');
select extensions.throws_ok($$select private.record_recommendation_event('unsupported')$$,'22023','unsupported recommendation event type','private implementation preserves defaults and validation');
reset role;
select * from extensions.finish();
rollback;
